language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - 12
  - 10
  - 8
before_install:
  - if [ "$TRAVIS_CPU_ARCH" = "ppc64le" ]; then 
      npm install generator;  # Install generator for ppc64le
      npm install -g;
    fi  
  - npm install --global npm@latest
after_success:
  - npm run coverage
